version: "3.8"
services:
  game-server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    container_name: game-server
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment: 
      NODE_ENV: development
